ci:
  autofix_prs: true
  autoupdate_schedule: monthly

repos:
  - repo: https://codeberg.org/frnmst/md-toc
    # Remember to keep md-toc up-to-date!
    rev: 8.2.0  # set a specific git tag
    hooks:
      - id: md-toc
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17  # Use the ref you want to point at
    hooks:
      - id: mdformat
        # Optionally add plugins
        additional_dependencies:
          - mdformat-black
